services:
  accsev-app:
    build: .
    image: srikar77/ykprojects:AccSevDetectionModel
    container_name: Accsev_app
    ports:
      - "5173:5173"
      - "5000:5000"
    volumes:
      - ./backend/watch_folder:/app/backend/watch_folder
    restart: unless-stopped